export const PARSE_ERROR = 'PARSE_ERROR';
export const INVALID_REQUEST = 'INVALID_REQUEST';
export const METHOD_NOT_FOUND = 'METHOD_NOT_FOUND';
export const INVALID_PARAMS = 'INVALID_PARAMS';
export const INTERNAL_ERROR = 'INTERNAL_ERROR';
export const SERVER_ERROR = 'SERVER_ERROR';
